// @ts-check
// NOTE: do not edit this file, it provides automated loading of modularized resolvers

import { join } from 'path'
import { mergeResolvers, fileLoader } from 'merge-graphql-schemas'

const resolversArray = fileLoader(join(__dirname, './**/*.resolv.*'))
export default mergeResolvers(resolversArray)
